name: Check AWS Identity
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
jobs:
  check-identity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Match your Terraform region
      - name: Run AWS STS Get-Caller-Identity
        run: aws sts get-caller-identity
