name: Terraform Plan  # Renamed for clarity

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to latest version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to latest version
        with:
          terraform_version: 1.8.0  # Standardized to match apply.yml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4  # Updated to latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_my_variable: "value"  # Kept as optional
